### ISSUE TITLE
HexViewer: View does not exist on desk!

### ISSUE THREAD

**Issue by funvill** [facelessuser/HexViewer#25]
Hello 

When attempting to switch between a ascii file to a hex view, I get the following error message. 

"HexViewer: Veiw does not exist on disk!" 
http://s.chipkin.com/files/2014/sep/HexViewError.PNG

This is the first packages I have installed via "package control" https://sublime.wbond.net an it may have something to do with my inexperience with package control. 

Using Sublime 3, build 3065

**Comment by WhiteHotLoveTiger** [comment]
I've just run into this error message when trying to view the hex of a string I pasted into a new sublime tab. It says that the "View" doesn't exist on disk. I didn't know what this meant. Is there some sort of "View" file for each file type? What the heck is going on?

I now understand the problem, but perhaps the error message could be changed to say something more helpful like, "Hexviewer can only show you files which have been saved to disk. Try saving this file and starting Hexviewer again."

**Comment by facelessuser** [comment]
That is fine.  I am open to pull requests; otherwise, I will put it on my list for when I sit down to fix issues.
