### ISSUE TITLE
Font configuration

### ISSUE THREAD

**Issue by yujun-zhang** [facelessuser/HexViewer#28]
How do I configure the font to be used under HexView? When I toggle to HexView, it seems to be using a different font and I could not change it with [Font Chooser](https://packagecontrol.io/packages/OSX%20Font%20Chooser)

![screen shot 2015-01-22 at 11 41 39 am](https://cloud.githubusercontent.com/assets/6813397/5850198/b814c7da-a22b-11e4-8aea-6a7dd0c0a5a3.png)

![screen shot 2015-01-22 at 11 41 55 am](https://cloud.githubusercontent.com/assets/6813397/5850197/b810c4be-a22b-11e4-8326-132043ab8e04.png)

**Comment by facelessuser** [comment]
```js
    // Use a custom font and/or font size in hex view.
    // Use None to use the current Sublime Text font.
    "custom_font" : "none",
```

You can set your font with the above setting in the settings file.

**Comment by yujun-zhang** [comment]
Great, it works. Thanks for the fast responding.

**Comment by yujun-zhang** [comment]
It seems this issue is raised several times.

I would suggest set a mono space font as default rather than "none". Everybody in hex view wants a mono space font.

**Comment by facelessuser** [comment]
> I would suggest set a mono space font as default rather than "none". Everybody in hex view wants a mono space font.

I agree, but I don't know what fonts are on everyone's computer, so I leave it to them to configure.  I mention in the documentation that this is configurable: https://github.com/facelessuser/HexViewer#configurable-settings.  I even leave comments about each setting in the settings file to make it easy on the user.  I feel this should be sufficient.

Not picking up the current font was a problem, but hopefully pull #27 has fixed this.  I merged it to the ST3 branch last night (ST2 is end of life and I no longer push fixes to that branch).

**Comment by bernfarr** [comment]
Could you add a comment that gives an example setting for fonts? When I view the config settings in hex I'm not seeing a monospaced font, I've tried `"custom_font" : "Consolas"` and `"custom_font" : "Courier New"` without success, I'm not sure whether I should use a font family name or something else.  Many thanks for a useful extension.

**Comment by bernfarr** [comment]
Never mind, I didn't restart after installation, now it's working with Courier New. Many thanks.
