### ISSUE TITLE
How to edit?

### ISSUE THREAD

**Issue by chexo3** [facelessuser/HexViewer#29]
I can't seem to figure out the edit panel. I keep trying but it keeps saying unexpected number of bytes. Can we get more intuitive hex and string editing, like the default hex view?

**Comment by facelessuser** [comment]
You edit bytes in place.  You can't currently insert extra bytes or remove bytes.  That is probably why you keep getting those errors.

> Can we get more intuitive hex and string editing, like the default hex view?

It's not as straight forward as you may think.  I am working with the limited infrastructure provided by the sublime API.  With that said, I do take pull requests if you come up with something more intuitive.

**Comment by chexo3** [comment]
How do I edit said bytes in place? I may know a bit about computers but not much about this. Also, same with the string editing!

**Comment by facelessuser** [comment]
Just select the bytes OR select characters on the right in the ascii section.  Select the edit command from the menu.  The panel will open showing the bytes you selected to edit.  Enter the new bytes (must be the same amount as it started with).  If you want to do strings, you must use start the entry with `s:` then followed by the string (must be the same amount of bytes).  Hit enter.

**Comment by chexo3** [comment]
Ok, trying that on an image. No seriously.

**Comment by chexo3** [comment]
It worked!

**Comment by facelessuser** [comment]
> It worked!

Of course it did :wink:.  Maybe I can make that a bit more clear in the documentation.  It really isn't that bad once you understand how it works, but I can see how it might not be obvious at first.
