### ISSUE TITLE
Binary search

### ISSUE THREAD

**Issue by rexdf** [facelessuser/HexViewer#33]
Using the sublime built-in search the address will stop you from searching continous binary bit.

If I delete the space between the hex word or mismatch the space, built-in search cannot tell the right result.

If I use some kind of complex regex, it maybe work for a while.

Binary or decimal or hex continous search. Allow space in user-input pattern string.

So how about a function for it?

**Comment by facelessuser** [comment]
I get why you want what you want, and this would be easier if sublime at a more rich plugin environment allowing me to effectively separate the binary data form the address column and ascii data etc., but it doesn't.  So then I would need to come up with a ridiculously complex regex to accomplish this, or keep a buffer of just the data in memory doubling the memory required to open a binary file so I could search that buffer instead.  I don't know, if I really need to search something that just isn't effective in sublime, I just open the file in an external hex editor via the `open in external viewer` command.

**Comment by facelessuser** [comment]
Closing this issue as it is quite stale. Unfortunately, I don't think I will be implementing such a feature.
