### ISSUE TITLE
cannot find hexviewer in sublime text 2 package control

### ISSUE THREAD

**Issue by StevenHuang4321** [facelessuser/HexViewer#34]

**Comment by facelessuser** [comment]
This sounds like a Package Control issue, not a HexViewer issue.

HexViewer is set up properly with PackageControl as you can see on its Package Control page, the correct tag is found for ST2: https://packagecontrol.io/packages/HexViewer.

If Package Control is not finding that for you locally, you may need to file an issue with them as everything is set up good on my side.

Another thing you can check is that you didn't already accidentally install HexViewer, as it will not show up as installable if it is already installed.
