### ISSUE TITLE
No Hex Inspector?

### ISSUE THREAD

**Issue by JarrettBillingsley** [facelessuser/HexViewer#35]
Sorry, I don't know how else to contact you so feel free to close this issue. I know the ST2 branch is not really officially supported, but is the Hex Inspector just not implemented in that version, or am I missing something? It doesn't appear in the command palette and the "inspector_auto_show" option seems to have no effect.

**Comment by facelessuser** [comment]
It's supposed to work.  I haven't fired up ST2 in a long time.  Hex Inspector was originally implemented on ST2, so I am a bit surprised it isn't working for you.  I guess its possible a regression was introduced right before I stopped supporting it, but you are the first I've heard from about such an issue, and I moved on from ST2 a long time ago.

**Comment by JarrettBillingsley** [comment]
I see. I guess I should try out ST3 anyway, even if it doesn't seem like the dev is doing much anymore :P

**Comment by Puccet** [comment]
Hi,

I've exactly the same issue but on ST3 3.1.1 build 3176

![schermata 2018-06-20 alle 13 53 40](https://user-images.githubusercontent.com/5746022/41656757-5f06ed6c-7491-11e8-899c-82bc35ba4bbd.png)
![schermata 2018-06-20 alle 13 51 37](https://user-images.githubusercontent.com/5746022/41656762-631c2610-7491-11e8-81b9-1a3e6a5016f8.png)

**Comment by facelessuser** [comment]
@Puccet, it is because your intel HEX syntax is overriding Hex Viewer's. Hex inspector won't open unless the syntax is its own hex syntax.

**Comment by Puccet** [comment]
Thank you! The point is that .hex extension is commonly used for IntelHex files, is it possibile to tell HexViewer to use a different one ? such as .hexviewer ? in this way it would not overlap with IntelHex or other hex format.
