### ISSUE TITLE
Executing the command "Hex Viewer: Toggle Hex View" has no effect in some cases

### ISSUE THREAD

**Issue by richardcd73** [facelessuser/HexViewer#36]
I had some installation trouble, and I'm not sure if it's a bug. I hope this is the right place to post.

Symptom: Executing the command "Hex Viewer: Toggle Hex View" has no effect.

Sublime Text version/build: 2.0.2 build 2221
Operating system: Mac OS 10.11.2
Errors in console: None (No Console Output whatsoever)

Detailed description of the problem: 
I installed hex viewer via Package Control. (I installed package control just before installing hex viewer. I got some errors when using the console, so I did it manually.) The console showed an issue with md2 hash, but this might be an unrelated problem. Full console output is below. After installing, use Cmd-Shift-P to bring up the command palette. The command "Hex Viewer: Toggle Hex View" is present, but executing it has no visible effect and produces no output to the console.

Here is the full console output after installing Hex Viewer via Package Control.
ignored packages updated to: [HexViewer, Vintage]
found 1 files for base name Default.sublime-theme
reloading /Users/noname/Library/Application Support/Sublime Text 2/Packages/User/Package Control.sublime-settings
reloading /Users/noname/Library/Application Support/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
theme loaded
reloading /Users/noname/Library/Application Support/Sublime Text 2/Packages/User/Package Control.sublime-settings
ignored packages updated to: [Vintage]
found 1 files for base name Default.sublime-theme
reloading /Users/noname/Library/Application Support/Sublime Text 2/Packages/User/Package Control.sublime-settings
reloading /Users/noname/Library/Application Support/Sublime Text 2/Packages/User/Preferences.sublime-settings
theme loaded
found 1 files for base name Default.sublime-theme
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/hex_checksum.py
Hex Viewer: md2 hash is not available!
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/hex_common.py
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/hex_editor.py
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/hex_finder.py
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/hex_highlighter.py
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/hex_inspector.py
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/hex_viewer.py
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/hex_writer.py
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/sum_hashes.py
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/tiger.py
Reloading plugin /Users/noname/Library/Application Support/Sublime Text 2/Packages/HexViewer/whirlpool.py
found 5 files for base name Default.sublime-keymap
found 3 files for base name Main.sublime-menu
theme loaded
Generating syntax summary
reloading /Users/noname/Library/Application Support/Sublime Text 2/Packages/User/Preferences.sublime-settings
found 1 files for base name Default.sublime-theme
theme loaded

**Comment by facelessuser** [comment]
1. Restart sublime after installing. 

2. You would have to give me a very specific, reproducible scenario to cause failure for me to offer any kind of advice or explanation. 

3. The hash warning is just because available hashes differ from system to system; you can ignore that warning. 

4. Beyond general advise,  the ST2 version is no longer supported.   I am only supporting the ST3 branch moving forward as I only use ST3 and supporting both on all the plugins I support is too much work.

**Comment by richardcd73** [comment]
1. I did restart several times.
2. I'm not sure what other specifics I could give. The installation appeared to complete without a hitch, and the Hex Viewer menu appeared under Tools->Packages. But executing the "Toggle Hex View" command has no effect in the UI or the Console, whether from using the menu, CMD-P, or keyboard shortcuts. 
3. Thanks.
4. If you're not supporting this, then I guess I'll give up unless you have any other suggestions. Perhaps I could try uninstalling Sublime Text and reinstalling it.

**Comment by facelessuser** [comment]
> I'm not sure what other specifics I could give. The installation appeared to complete without a hitch, and the Hex Viewer menu appeared under Tools->Packages. But executing the "Toggle Hex View" command, whether from using the menu, CMD-P, or keyboard shortcuts, has no effect in the UI or the Console.

The latest Hex Viewer works for me in my ST2 install.  I just fired it up with the latest.  I don't really use ST2 anymore, but it is still installed on my OSX system.  I can't reproduce your problem, so I can only assume it is something specific with your setup, unless you can give me a specific scenario I can reproduce.  I hope that makes sense.

> If you're not supporting this, then I guess I'll give up unless you have any other suggestions. Perhaps I could try uninstalling Sublime Text and reinstalling it.

That may be a good idea.  Like I said it is working for me.  I don't know what else I could suggest.  I hope you get it working.

**Comment by richardcd73** [comment]
I just switched to ST3. After I did this, I tried to reproduce the problem, and I noticed that a new dialog box showed up saying "HexViewer: View does not exist on disk!". So I guess that was the problem, the old version did not show me the dialog box, it merely failed without a warning. If you're not supporting the ST2 version any more, then I guess this isn't worth fixing. Thanks.

**Comment by facelessuser** [comment]
Okay, that makes sense.  Glad you got it figured out.

**Comment by romiro** [comment]
For what it's worth, I was having the exact same issue until I saved the data I was trying to view to disk. Then I was able to use HexViewer.
