### ISSUE TITLE
Support Additional Text Encodings in Hex Viewer

### ISSUE THREAD

**Issue by richardcd73** [facelessuser/HexViewer#37]
Sublime Text 3 build: 3083
Operating system: Mac OS 10.11.2
Errors in console: None
Detailed description of the problem: It would be awesome if hex viewer supported unicode text by showing the appropriate unicode characters on the right whenever Sublime Text shows the right thing. This would be a reasonably big UI change, since a character is more than one byte, but some very simple approaches might be good enough. For example, you could use the Unicode rules to look up the appropriate glyph and show it (if available) in the slot for the first byte, and then still fill in the remaining bytes with "." to keep exactly 24 glyphs per row.

Reproduction Steps:
1. Create a new text file in Sublime Text and paste in the following text: "Hello 人亻𠆢龟龜". This should appear as "Hello " followed by five Chinese characters. (You may need to install a Chinese font first.)
2. Save the file.
3. Toggle to hex view. The text at the right will show "Hello ................" (sixteen dots).

**Comment by facelessuser** [comment]
I would say HexViewer doesn't support **any** Unicode chars.  HexViewer only shows ASCII characters.

**Comment by richardcd73** [comment]
Fair enough. I just thought I would put in a vote for unicode support and offer a test case, if you ever want to try.

**Comment by facelessuser** [comment]
I guess I am not sure how to approach Unicode as I am not expected to know the encoding of the file.  I know some hex viewers can show Unicode chars, but I am not really sure the approach they normally take in this matter or even if it makes sense.  I honestly haven't put much thought into supporting Unicode chars. If I were to consider Unicode char support, I guess I would be interested in some kind of proposal on how to tackle it first.

**Comment by richardcd73** [comment]
My sense is that most hex viewers don’t bother with this, you’re right. Those that do tend to assume that the entire file is encoded as ASCII or UTF-8, etc. If I were going to do this, I would try to find out what encoding ST is using to display the file, and I’d use that encoding in the hex view, though I might allow someone to switch to another encoding.

I haven’t made any plugins before, so I don’t know how hard it is to find out the encoding that ST is using for display. I only know that you can re-open the file with a different encoding and see something different, so the information is around at some point. I also don’t know how easy it is to work with the various encodings that ST supports.

Thanks for entertaining the idea. If I get really motivated, maybe I’ll try to do this myself.

**Comment by facelessuser** [comment]
Encoding detention is hard.   Most real binary files (not text files viewed as binary) don't have an encoding per se as they are mainly data with some encoded strings inside.   This would make encoding detection hard as you would have to know the structure of the binary file in order to find the string instances to then run through an encoding detector (which may be inaccurate unless you run a large enough text sample through it).   In general I think it would be too much work for an unreliable result.

**Comment by richardcd73** [comment]
I didn’t mean for HexViewer to do encoding detection. I just thought it might be possible to piggy-back on ST’s encoding detection and allow the user to select a new encoding as a backup. But you are right that this wouldn’t work for arbitrary binary files; it would only work if the entire file was text. You could deal with arbitrary binary files by allowing the user to specify the first byte and encoding for each text string, but that would be a lot more complicated and probably isn’t worth it.

**Comment by facelessuser** [comment]
> I didn’t mean for HexViewer to do encoding detection. I just thought it might be possible to piggy-back on ST’s encoding detection and allow the user to select a new encoding as a backup. 

Understood.  I guess this would only work for plain text files, but I rarely have to open those up in a hex view.

I think for now I will close this issue as ASCII seems to be sufficient for what I want.  I am open to pull requests for Unicode display if a sane Unicode handler can be constructed, but I don't think it is something I want to put effort into myself.

Thanks for the feedback though; I find it useful to discuss things I haven't considered before.

**Comment by richardcd73** [comment]
No problem. Thanks again for considering it.
