### ISSUE TITLE
HexViewer refuses to load file larger than 50000.0KB.

### ISSUE THREAD

**Issue by leetNightshade** [facelessuser/HexViewer#38]
I realize this is a config setting, so locally I do have this changed so I can get by this limit. But it made me wonder, instead of preventing the user from doing this, can you pop up a warning instead? This is a design decision you made, why not make things more flexible for the user? Thanks for at least making it a config option I can override in my user config.

**Comment by facelessuser** [comment]
It is possible that the limit can trigger a dialog instead of a hard denial.  I think I would be okay with that.
