### ISSUE TITLE
Hex Inspector does not close when closing a file opened in Hex View

### ISSUE THREAD

**Issue by Ricq** [facelessuser/HexViewer#40]
**Scenario**
 * Open a file
 * Enable the HexView by using Ctrl-Shift-P: `Hex Viewer: Toggle Hex View`
 * Verify that the Hex Inspector view is shown at the bottom of the screen
 * Close the active file using Ctrl-F4

**Expected result**
 * The Hex Viewer with the open file closes, and the Hex Inspector view is closed as well

**Actual result**
 * The open file closes, but the Hex Inspector view at the bottom remains open, until the Hex Viewer is explicitly enabled and disabled again.

**Comment by facelessuser** [comment]
You can also always just hit the ESC key.  That dismisses any panel in Sublime.  That was always how it was supposed to be dismissed.  Only recently does HexViewer close the inspector on toggle off.  I currently don't have an on_close event to capture and execute this. If I get some time soon I can look into adding one.

**Comment by Ricq** [comment]
Thanks for the workaround. The ESC key indeed just works. I do think it would be an improvement though if it closed along with the file that was closed. It would be great if you could indeed add that one.
