### ISSUE TITLE
Rename the command "Find by Address" into "Go to Offset"

### ISSUE THREAD

**Issue by darkred** [facelessuser/HexViewer#41]
Thanks for this great package.

I'd like to make just one suggestion:
to rename the command in Tools|Packages|HexViewer|`Find by Address` into `Go to offset`.
That's because this command is equivalent to "Go to a specific offset" - it's not performing a search.

**Comment by facelessuser** [comment]
I find nothing wrong with the current name.  Getting into the semantics of what qualifies a search isn't something I am interested in.

With that said, if this is something that is bothersome, I am open to pull requests.

**Comment by darkred** [comment]
I changed [all mentions](https://github.com/facelessuser/HexViewer/search?utf8=%E2%9C%93&q=%22find+by+address%22) of "Find by Address"
and slightly changed the relevant entry in User Guide (`usage.md`)

**Comment by facelessuser** [comment]
Thanks for taking the time to create the pull.  I will merge it later today.

**Comment by darkred** [comment]
> I will merge it later today.

Thank you for accepting to merge my pull request 
(I hope you haven't changed your mind)

**Comment by facelessuser** [comment]
Nope just got busy.  Still in the plan.
