### ISSUE TITLE
Add further settings options

### ISSUE THREAD

**Issue by St0fF-NPL-ToM** [facelessuser/HexViewer#43]
I'd like to have the ability to choose the output-format in the Hex Inspector more fine grained.

Could you add preferences, so every single output's type can be changed?
I.e.: I'd like to see DWORDs as Hex, so I changed `"inspector_integer_format": "%-12s:  0x%-22X"` - but now all integer values, from byte up to long long int are in the same hex-format.  It should be possible to define a special output format for any of those values listed.

**Comment by facelessuser** [comment]
> I'd like to see DWORDs as Hex

Isn't everything already in Hex?  The inspector is meant to translate it into readable non-hex units.  What is the point of taking hex and re-displaying it in the inspector?  I'm afraid I just can't see the usefulness of this yet.

**Comment by St0fF-NPL-ToM** [comment]
The point is Endian Transformation, ready for Copy'n'Paste.  But well, I can live with it as it is.

**Comment by facelessuser** [comment]
I think for now I am going to pass on this.  Thanks for the request though.
