### ISSUE TITLE
Reload file command

### ISSUE THREAD

**Issue by Drakim** [facelessuser/HexViewer#44]
While Sublime keeps track of file changes in the background and automatically reloads them, HexViewer does not do so (I assume because the conversion process is rather heavy).

I suggest implementing a reload file command (that the user could map up to a hotkey if he wanted). Currently the best I can do is exit and re-enter HexViewer mode in Sublime, which forces the file to reload, but also loses my place in the file.

**Comment by facelessuser** [comment]
I will consider a manual reload.  It probably won't preserve edits though.
