### ISSUE TITLE
Option for Uppercase Hex

### ISSUE THREAD

**Issue by Adarma** [facelessuser/HexViewer#46]
Could you add a setting to display the Hex in uppercase: 0123456789ABCDEF

**Comment by facelessuser** [comment]
I could; I'm not against it.  If I get some time I will add it.

**Comment by facelessuser** [comment]
Actually didn't take long.  I will probably tag a release soon.  I think I got all the hex refrences, but if I missed some hex value reference, just open a new issue.

**Comment by Adarma** [comment]
Thanks, looks good
