### ISSUE TITLE
How edit text in HexViewer?

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/HexViewer#51]
See how I edit the text in my editor 010 Editor.

![010 Editor](http://i.imgur.com/qu1Y5Tv.gif)

Is it possible to do so in HexViewer? I read documentation and I found only command `hex_editor` that edits bytes, no text.

Thanks.

**Comment by Kristinita** [comment]
O'h, I'm sorry, I entering `S:This`, ho `s:This`. Unfortunately, I can not delete issue.

**Comment by facelessuser** [comment]
Glad you figured it out.
