### ISSUE TITLE
No installation instructions, basic usage docs

### ISSUE THREAD

**Issue by skaffen2** [facelessuser/HexViewer#55]
Hi,

Can I suggest adding installation instructions to the readme?  And basic usage instructions?  I tried extracting the release zip to the packages folder, but didn't see how to switch to hex mode.

Thanks.

**Comment by facelessuser** [comment]
There is a link to the docs on the readme.

**Comment by skaffen2** [comment]
oh, sorry, I missed that, was rushing too much.
