### ISSUE TITLE
Use Insert Mode to Get Underline Caret

### ISSUE THREAD

**Issue by garyemerson** [facelessuser/HexViewer#58]
The underline caret used for insert mode is more visually accurate for hex viewing since it's always directly under one individual character instead of between.

Current:
![bar_caret](https://cloud.githubusercontent.com/assets/5726308/22355972/d6fb943a-e3e2-11e6-868d-7151e4f29e8f.gif)

Proposed:
![underline_caret](https://cloud.githubusercontent.com/assets/5726308/22355977/df02d468-e3e2-11e6-9742-406ad242802c.gif)

Just something to consider. If it doesn't pose any other complications it might be worth the small change.

**Comment by facelessuser** [comment]
It is something that people could easily implement outside of HexViewer as well. It is a personal preference thing.  To me, it makes no difference.  But I'll consider it.

**Comment by facelessuser** [comment]
This issue is stale. I currently have no plans to implement this.
