### ISSUE TITLE
[Feature request] Disable for extensions

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/HexViewer#59]
### 1. Request

It would be nice, if you add option `disabled_extensions` for HexViever. I don't find in HexViewer documentation, how I can do it.

### 2. Justification

For example, I can view content of my `zip` files use [**ZipBrowser**](https://bitbucket.org/klorenz/sublimezipbrowser/src) package. It conflicts with HexViewer. I don't want use HexViewer for `zip`, but I want to use HexViewer for some other extensions.

### 3. Desirable behavior

I add in my `User\hex_viewer.sublime-settings` 

    "disabled_extensions": [".zip"]

HexViewer don't work, if I open `zip` file in Sublime Text, but work for other binary files.

Thanks.

**Comment by facelessuser** [comment]
I believe this can already be accomplished with current settings.  I will explain.

There are two settings that control what HexViewer auto-converts to a HexViewer output: 

```
    // Disable auto open based on 'Hexidecimal' encoding
    "disable_auto_open_hex_encoding": false,

    // Auto open patterns to open in hex viewer
    "auto_open_patterns" : ["*.bin", "*.pyc"],
```

By default, HexViewer converts **any** file that is opened as `hexidecimal` syntax.  Sublime, in `Preferences.sublime-settings` specifies which files it opens as `hexidecimal` syntax.  Sublime states that it hides these files from "Goto Anything", but if memory serves me correctly, files specified below also get shown as `hexidecimal` files (except images which get routed through the image previewer).

```
    // These files will still show up in the side bar, but won't be included in
    // Goto Anything or Find in Files
    "binary_file_patterns": ["*.jpg", "*.jpeg", "*.png", "*.gif", "*.ttf", "*.tga", "*.dds", "*.ico", "*.eot", "*.pdf", "*.swf", "*.jar", "*.zip"],
```

So with HexViewer's setting `disable_auto_open_hex_encoding` set to `false`, everything in `binary_file_patterns` (except images), will get converted to HexViewer output.  You can enable this setting and HexViewer will no longer convert those.

The second setting is the explicit `auto_open_patterns` which tells HexViewer, these extensions should get  converted.  So, by enabling `disable_auto_open_hex_encoding`, HexViewer will only reference `auto_open_patterns`. Then you can add or remove any binary files you want HexViewer to handle there.

Let me know if for any reasons that is not the actual behavior.

**Comment by Kristinita** [comment]
@facelessuser, second method worked for me. I add whitelist of extensions, which I want to open in HexViewer.

First method not worked for me:

If `"disable_auto_open_hex_encoding": false`

   + `zip` files don't open in HexViewer,
   + `exe` files also don't open in HexViewer.

If I copy line

    "binary_file_patterns": ["*.jpg", "*.jpeg", "*.png", "*.gif", "*.ttf", "*.tga", "*.dds", "*.ico", "*.eot", "*.pdf", "*.swf", "*.jar", "*.zip"],

to `User\Preferences.sublime-settings` file → I also get same behavior.

Thanks.

**Comment by facelessuser** [comment]
> If `"disable_auto_open_hex_encoding": false`
>
> - zip files don't open in HexViewer,
> - exe files also don't open in HexViewer.

Right, this is what I would expect, because then HexViewer is **only** using `auto_open_patterns`, which doesn't have `*.exe` defined, but you can add it :wink:.  Anyways, As long as you got it working how you like it, that's what's important.
