### ISSUE TITLE
column select causes sublime stuck

### ISSUE THREAD

**Issue by shanehou** [facelessuser/HexViewer#63]
Ctrl+Shift+P, Toggle Hex View, Column Select (Shift + Right Mouse Button)...
Then Sublime would get stuck.
Windows 7, Sublime Text 3 build 3126

**Comment by facelessuser** [comment]
I have no idea how big your file is or what your settings are.  This bug description is too vague.

With that said, you ensure highlight throttle is turned on and set it to an acceptable limit for your machine.

```js
     "highlight_max_bytes" : 1000,
    "highlight_throttle" : true,
```

Also, I'll be frank, I would upgrade to the latest stable release as I will no longer be installing and debugging versions later than the stable release.

**Comment by facelessuser** [comment]
Almost a month and no further details.  Closing as there is no actionable item.
