### ISSUE TITLE
Have Hexviewer to use a custom extension to don't override other hex format

### ISSUE THREAD

**Issue by Puccet** [facelessuser/HexViewer#65]
The point is that .hex extension is commonly used for IntelHex files, it would be great  to have HexViewer to use a different one, such as .hexviewer ? in this way it would not overlap with IntelHex or other hex format.

**Comment by facelessuser** [comment]
`.hex` is not exclusive to Intel hex files.  `.hex` is used for lots of hex files, but it is possible that I might make it configurable when I have time. It's possible I may just adopt something like `.hexviewer` or something else like `.hxv`.

**Comment by facelessuser** [comment]
Better late than never, but we will now use `.hxv` as the extension.
