### ISSUE TITLE
HexViewer doesn't appear in Sublime Text 2 Package List

### ISSUE THREAD

**Issue by Galadros** [facelessuser/HexViewer#72]
I'm trying to install this package, and it simply doesn't show up in my package list when I try.  I have Packet Manager installed and working and all that; I can see plenty of other packages to add, but HexViewer simply doesn't show up.  I'm using Sublime Text 2 on Ubuntu 16.04, if that helps.

**Comment by facelessuser** [comment]
HexViewer is only supported on ST3. You can install it manually from the old ST2 branch though: https://github.com/facelessuser/HexViewer/tree/ST2. But keep in mind that there is no support for ST2.

It was just too much for me to support all the plugins I do on both ST2 and ST3.

**Comment by Galadros** [comment]
Ah, thank you- I appreciate the head's up.
