### ISSUE TITLE
select hex/ascii over 2 or more lines

### ISSUE THREAD

**Issue by jojoTheBearded** [facelessuser/HexViewer#75]
I'm pretty confused about this: I need to copy some hex values from a file, 36 bytes in total, so that's more than one line. Unfortunately HexViewer doesn't allow me to do that (because it selects the ascii as well). 
Am I missing something? If not, imho this (selecting _only_ the hex values / selecting _only_ the ascii, across 2 or more lines) is a feature that's absolutely essential.

**Comment by facelessuser** [comment]
<kbd>shift</kbd> + <kbd>right click</kbd> and drag?  Shortcut is for Windows, as that is the machine I am currently sitting in front of, I forget if it is the same on mac and Linux.

In short, Sublime can do column selections, so you'll have to use that.

**Comment by jojoTheBearded** [comment]
Ah ok, I dind't know that. So yeah, that kind of works, but there's clearly room for improvement in HexViewer there.

**Comment by facelessuser** [comment]
HexViewer is simply converts a file to a hex view. Unfortunately, the Sublime API does not really provide contains in a view, You can split the Window into multiple views, and if you restrict wrapping, you could maybe get an interface that does what you want, but that is awkward. There really just isn't an easy way to get exactly what is desired, so column select is the best there is currently.

FWIW, HexViewer does exactly what I want from it.  It is not a fully featured hex editor, but it gives you a reasonable hex view. That is really it's purpose, a quick way to check out some binary data.
