### ISSUE TITLE
Please add the possibility to view qwords as UNIX timestamps

### ISSUE THREAD

**Issue by ratcashdev** [facelessuser/HexViewer#77]
... formatted as ISO-8601 to the bottom panel.

Great plugin, anyway!

**Comment by facelessuser** [comment]
Can you link documentation?

**Comment by ratcashdev** [comment]
sure: https://en.wikipedia.org/wiki/Unix_time
here is a handy online converter: https://www.epochconverter.com/

**Comment by facelessuser** [comment]
I'll consider it. It isn't high priority, but if/when I get some time, I'll take a look.

**Comment by facelessuser** [comment]
I've looked this over and this shouldn't be a problem to add. I have a quick a dirty patch that has this working locally. I'll post a branch for testing once I upload it.

@gir-bot remove P: maybe
