### ISSUE TITLE
Package Control Won't Install - Missing Dependency

### ISSUE THREAD

**Issue by gyrfalcon2138** [facelessuser/HexViewer#78]
Using SublimeText V 3.2.1 Build 3207, Package Control V 3.3.0

Trying to install HexViewer via Package Control: Install Package - HexViewer package will not install.

Checking the console, I get the following message during install attempt:

Package Control: The dependency 'pygments' is not currently installed; installing...
Package Control: The dependency 'pygments' has successfully been installed or updated
Package Control: The dependency 'python-markdown' is not currently installed; installing...
Package Control: The dependency 'python-markdown' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' has successfully been installed or updated
**Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' is not available
Package Control: The dependency 'python-jinja2' could not be installed or updated**

Running Windows 7, if there's any other relevant info I can provide let me know.

**Comment by facelessuser** [comment]
This is a package control problem: https://github.com/wbond/package_control/issues/1430.

You can attempt a workaround found here: https://forum.sublimetext.com/t/python-jinja2-package-install-problem/29120.

But there is nothing that I can do. This must be fixed in Package Control.

**Comment by gyrfalcon2138** [comment]
This is super helpful and looks like it works. Had to do the same steps for the markupsafe package and someone linked to https://github.com/SublimeText/LaTeXTools/issues/1414 about that.

Thanks much @facelessuser.
