### ISSUE TITLE
Hex Inspector shows incorrect information

### ISSUE THREAD

**Issue by sok0** [facelessuser/HexViewer#79]
The Hex Inspector only shows the currently selected byte correctly but then incorrectly also displays other non-byte data types such as for example, word, int, etc. These other data types are more than one byte long so their representation as a single byte is meaningless. If you try to multi-select in the hex editor two bytes then the Hex Inspector blanks out with "--". It looks to me like the script attempts to zero out the other bytes for the other data types but if that is the case then the calculation is gone because the numbers don't add up when comparing to a real hex editor like HxD.

**Comment by sok0** [comment]
I had the wrong endian turned on

**Comment by facelessuser** [comment]
Yup, endianness matters. Gad you figured it out.
