### ISSUE TITLE
Cannot install it

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [facelessuser/HexViewer#80]
When I try it to install it on Linux 64 bits in Sublime text version 3.2.2, here is the result:

```
Unable to download HexViewer. Please view the console for more details.
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["HexViewer", "Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
Package Control: Error downloading package. URL error [Errno 104] Connection reset by peer downloading https://codeload.github.com/facelessuser/HexViewer/zip/st3-2.6.4.
error: Package Control
```

**Comment by DavidPerezIngeniero** [comment]
Finally managed to install it manually by downloading the release archive and copying it into `~/.config/sublime-text-3/Installed Packages/`  I've compressed everything in a zip file called `HexViewer.sublime-package`.

**Comment by facelessuser** [comment]
Sounds like it could be a temporary issue with Package Control. I'd create an issue there. HexViewer is meant to be installed via Package Control as I believe it also links to some dependencies, but you have core functionality work fine by trying to install manually.

Anyways, this not a direct issue with HexViewer that I am aware of as I use it through PackageControl (except when I am developing on it).

If you are still having issues, I'd create an issue over at Package Control.
