### ISSUE TITLE
How do I get this working?

### ISSUE THREAD

**Issue by 5p0ng3b0b** [facelessuser/HexViewer#84]
I read the documentation and installed via package control but I can't figure out how to view files with this. If I open a hex file, I get the same view as I did before installing. Could you please explain what am I doing wrong?
![Screenshot](https://user-images.githubusercontent.com/12113595/74386497-05052580-4dee-11ea-9701-cbb2390a5b61.png)

**Comment by facelessuser** [comment]
You can always toggle with the command from the command palette as outlined in the docs: https://facelessuser.github.io/HexViewer/#hexviewer-toggle-hex-view.

You can also enable `auto_enable`: https://facelessuser.github.io/HexViewer/#auto_open.
You can configure file types that it triggers on: https://facelessuser.github.io/HexViewer/#auto_open_patterns

Basically, it is all in the documentation.

@gir-bot remove S: triage
@gir-bot add T: support

**Comment by facelessuser** [comment]
Hopefully that helps. If anything is unclear in the docs, or you are having issues getting what it described to work, feel free to reopen the issue with console errors or specific questions.
