### ISSUE TITLE
Insane amount of Memory used

### ISSUE THREAD

**Issue by TimeMaster18** [facelessuser/HexViewer#85]
Tried using the plugin today and run into an insane amount of memory used for "big" files.

I know the default maximum supported is 50MB but I have a decent PC and wanted to try so I opened a 330MB File with the plugin.

It took about 10 min and when opened, although smooth, it was using 10GB of memory.

I can't really wrap my head around on how a file of 330MB could need the usage of memory of 30x time its size, so I thought that it might be worth opening an issue.

![image](https://user-images.githubusercontent.com/50962671/123285131-134c7100-d50d-11eb-81c5-651c73bc47bd.png)
![image](https://user-images.githubusercontent.com/50962671/123285265-2f501280-d50d-11eb-872f-2ac5c4a37966.png)

Settings used: 
![image](https://user-images.githubusercontent.com/50962671/123285691-8f46b900-d50d-11eb-8f6b-1ad9ad3fd46a.png)

**Comment by facelessuser** [comment]
I suspect that this is a Sublime issue and not a HexViewer issue.

Initially, during conversion, yes we have to pull the whole file into memory, convert all the bytes to a visual representation, etc. But once that is done, the file is closed and all you are left with is a syntax-highlighted view. We (HexViewer) aren't storing tons of info in memory, we are operating on specific bytes based on scoping done via syntax highlighting.

For instance, when you place the cursor on a byte, we check the scope, convert the bytes for the inspector window and highlight the region in a view. That's it.

I imagine Sublime is holding a lot of info in memory. It may be indexing certain scopes for "Go To Anything", holding info for all the syntax highlighted scopes (color, region info, etc).

I imagine you'd see a similar jump just loading a 300 MB JavaScript file with no HexViewer installed. A matter of fact, I imagine you'll see a big difference just between a 300 MB plain text file and a 300 MB syntax highlighted file.

Personally, I don't ever use HexViewer for extremely large files. I'm often working with more reasonably sized hex files. I use it for quickly viewing hex files in the KB range. Sometimes in the small MB range. If I need to view a high MB or GB file, I'm often using a dedicated hex viewing app.

**Comment by TimeMaster18** [comment]
Fair, when opening the same file without the plugin, it goes up to about 5x the size memory used (1GB+), then with the plugin it multiplies by 10x again.

You are right about using a proper tool, was just curious if it could handle it but I guess not really :)

**Comment by facelessuser** [comment]
> Fair, when opening the same file without the plugin, it goes up to about 5x the size memory used (1GB+), then with the plugin it multiplies by 10x again.

The explosion of memory has nothing to do with the plugin, but everything to do with syntax highlighting.
