### ISSUE TITLE
Index on left not starting from zero

### ISSUE THREAD

**Issue by BacchusFLT** [facelessuser/HexViewer#87]
* Don't laugh but what I use it mainly for it hex view of commodore 64 files. Your numbering in the left is the index in the file. The C64 program file format has a word (in low/hi format) that tells the start address. I would welcome an option/mode where the tool would pick the first word and use that as the baseline for the index count. So this would mean two things: basing the index on something else than 0 and also using the first word as that basis.

**Comment by facelessuser** [comment]
I would need to think about this one. This is a very niche behavior. While I understand why it would be useful, given your specific context, it targets a very small audience.

@gir-bot add: T: feature, S: needs-decision
@gir-bot remove: s: triage

**Comment by BacchusFLT** [comment]
I sure understand that I could be the only one whom would be interested in this specific use case.

I was more thinking if this could be generalised. One would be the function to add an offset to the index.

The other would be a header parsing that would read a number of bytes that wouldn't be viewable as the binary payload. If that could also extract values that would use the adjusted index, the the function would be general.

**Comment by facelessuser** [comment]
There are probably numerous binary files with specific structures with additional metadata that could be extracted. I will consider it, but I cannot promise whether I will spend the time on such a task. HexViewer is meant as a fairly simplistic hex viewer and even more limited editor.

@gir-bot add P: maybe

**Comment by BacchusFLT** [comment]
Indeed there is a plethora of formats, and adding that is opening a can of
worms.

/Pontus Berg
 Bergatrollet AB
 CEO & Owner
 Tel/SMS: +46 735 082860
 www.bergatrollet.se


Den lör 31 juli 2021 kl 18:42 skrev Isaac Muse ***@***.***>:

**Comment by facelessuser** [comment]
Closing this issue as we have no plans at this time to pursue this request.
