### ISSUE TITLE
Discard prompt upon toggling hex view

### ISSUE THREAD

**Issue by cyzhou1028** [facelessuser/HexViewer#89]
After editing some hex, when I go to toggle hexview off, there is a prompt that asks whether to discard changes or not. Upon entering "no", hexview will just not be toggled off. There seems to be no way to make hex edits and then untoggle hexviewer in a way that preserves edits.

**Comment by facelessuser** [comment]
Hmm, I'll look into it and see if I can reproduce it., if so, I should be able to get a fix out. If not, I may need more information.

**Comment by facelessuser** [comment]
Going back over the code, I don't think this is a bug. You need to either discard the content or export the content back to the original source or a new source. Toggling hex view will not auto export back to a binary. You need to call the export command before toggling back as toggling will release the hex view from memory if you do not, along with all your edits.

I don't often edit hex files and mainly use the plugin to view them, so I had forgotten what the intention was.

**Comment by facelessuser** [comment]
Closing issue per last comment
