### ISSUE TITLE
Set hash to hex_checksum command

### ISSUE THREAD

**Issue by nicolasgomez1** [facelessuser/HexViewer#90]
Sorry to ask this here, but the way I see it, it's the most direct way to contact the plugin developer. I have a question about whether it is possible to assign the type of hash to the hex_checksum command? I have a shortcut
```
{
"keys": ["ctrl+shift+c"],
"command": "hex_checksum",
}
```
I saw that md5 is defined by default, and I would like to change it to crc32, is it possible to pass some argument to change to crc32 directly, without having to select it manually in the panel?

**Comment by facelessuser** [comment]
That should be it.

```js
{
"keys": ["ctrl+shift+c"],
"command": "hex_checksum",
"args": {"panel": false, "hash_algorithm": "crc32"}
}
```
